<?php

namespace Database\Seeders;

use App\Models\RecyclingCenter;
use App\Models\WasteType;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RecyclingCenterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get waste types for relationships
        $batteryType = WasteType::where('name', 'Battery')->first();
        $biologicalType = WasteType::where('name', 'Biological')->first();
        $brownGlassType = WasteType::where('name', 'Brown Glass')->first();
        $cardboardType = WasteType::where('name', 'Cardboard')->first();
        $clothesType = WasteType::where('name', 'Clothes')->first();
        $greenGlassType = WasteType::where('name', 'Green Glass')->first();
        $metalType = WasteType::where('name', 'Metal')->first();
        $paperType = WasteType::where('name', 'Paper')->first();
        $plasticType = WasteType::where('name', 'Plastic')->first();
        $shoesType = WasteType::where('name', 'Shoes')->first();
        $trashType = WasteType::where('name', 'Trash')->first();
        $whiteGlassType = WasteType::where('name', 'White Glass')->first();

        // Create centers for each state in Malaysia
        $centers = [
            // Johor
            [
                'name' => 'Johor Eco Recycling Hub',
                'address' => '15 Jalan Skudai, Johor Bahru, Johor 81300',
                'phone' => '(07) 555-1234',
                'latitude' => 1.4927,
                'longitude' => 103.7414,
                'hours' => [
                    'monday' => '8am - 6pm',
                    'tuesday' => '8am - 6pm',
                    'wednesday' => '8am - 6pm',
                    'thursday' => '8am - 6pm',
                    'friday' => '8am - 12pm, 2:30pm - 6pm',
                    'saturday' => '9am - 4pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://johorecorecycling.example.com',
                'waste_types' => [$plasticType, $paperType, $metalType, $cardboardType],
            ],
            [
                'name' => 'Muar Green Resources',
                'address' => '78 Jalan Ibrahim, Muar, Johor 84000',
                'phone' => '(06) 555-9876',
                'latitude' => 2.0442,
                'longitude' => 102.5689,
                'hours' => [
                    'monday' => '9am - 5pm',
                    'tuesday' => '9am - 5pm',
                    'wednesday' => '9am - 5pm',
                    'thursday' => '9am - 5pm',
                    'friday' => '9am - 12pm, 2:30pm - 5pm',
                    'saturday' => '10am - 3pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://muargreen.example.com',
                'waste_types' => [$brownGlassType, $greenGlassType, $whiteGlassType, $batteryType],
            ],
            [
                'name' => 'Kluang Recycling Station',
                'address' => '23 Jalan Mersing, Kluang, Johor 86000',
                'phone' => '(07) 555-3456',
                'latitude' => 2.0301,
                'longitude' => 103.3185,
                'hours' => [
                    'monday' => '8am - 7pm',
                    'tuesday' => '8am - 7pm',
                    'wednesday' => '8am - 7pm',
                    'thursday' => '8am - 7pm',
                    'friday' => '8am - 12pm, 2:30pm - 7pm',
                    'saturday' => '9am - 5pm',
                    'sunday' => '10am - 2pm',
                ],
                'website' => 'http://kluangrecycle.example.com',
                'waste_types' => [$biologicalType, $clothesType, $shoesType, $trashType],
            ],
            
            // Kedah
            [
                'name' => 'Alor Setar Recycling Hub',
                'address' => '45 Jalan Sultan Badlishah, Alor Setar, Kedah 05100',
                'phone' => '(04) 555-1122',
                'latitude' => 6.1263,
                'longitude' => 100.3673,
                'hours' => [
                    'monday' => '8am - 6pm',
                    'tuesday' => '8am - 6pm',
                    'wednesday' => '8am - 6pm',
                    'thursday' => '8am - 6pm',
                    'friday' => '8am - 12pm, 2:30pm - 6pm',
                    'saturday' => '9am - 4pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://alorsetarrecycling.example.com',
                'waste_types' => [$metalType, $paperType, $plasticType, $biologicalType],
            ],
            [
                'name' => 'Sungai Petani Green Center',
                'address' => '12 Jalan Patani, Sungai Petani, Kedah 08000',
                'phone' => '(04) 555-7890',
                'latitude' => 5.6475,
                'longitude' => 100.4876,
                'hours' => [
                    'monday' => '9am - 5pm',
                    'tuesday' => '9am - 5pm',
                    'wednesday' => '9am - 5pm',
                    'thursday' => '9am - 5pm',
                    'friday' => '9am - 12pm, 2:30pm - 5pm',
                    'saturday' => '10am - 3pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://sungaipetanigreen.example.com',
                'waste_types' => [$whiteGlassType, $brownGlassType, $greenGlassType, $cardboardType],
            ],
            [
                'name' => 'Kulim Waste Management',
                'address' => '67 Jalan Kulim, Kulim, Kedah 09000',
                'phone' => '(04) 555-2468',
                'latitude' => 5.3809,
                'longitude' => 100.5616,
                'hours' => [
                    'monday' => '8am - 7pm',
                    'tuesday' => '8am - 7pm',
                    'wednesday' => '8am - 7pm',
                    'thursday' => '8am - 7pm',
                    'friday' => '8am - 12pm, 2:30pm - 7pm',
                    'saturday' => '9am - 5pm',
                    'sunday' => '10am - 2pm',
                ],
                'website' => 'http://kulimrecycle.example.com',
                'waste_types' => [$clothesType, $shoesType, $batteryType, $trashType],
            ],
            
            // Kelantan
            [
                'name' => 'Kota Bharu Recycling Center',
                'address' => '22 Jalan Sultan Yahya Petra, Kota Bharu, Kelantan 15200',
                'phone' => '(09) 555-3344',
                'latitude' => 6.1331,
                'longitude' => 102.2437,
                'hours' => [
                    'monday' => '8am - 6pm',
                    'tuesday' => '8am - 6pm',
                    'wednesday' => '8am - 6pm',
                    'thursday' => '8am - 6pm',
                    'friday' => '8am - 12pm, 2:30pm - 6pm',
                    'saturday' => '9am - 4pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://kotabharurecycling.example.com',
                'waste_types' => [$paperType, $cardboardType, $plasticType, $whiteGlassType],
            ],
            [
                'name' => 'Pasir Mas Green Point',
                'address' => '8 Jalan Ismail Petra, Pasir Mas, Kelantan 17000',
                'phone' => '(09) 555-5678',
                'latitude' => 6.0346,
                'longitude' => 102.1434,
                'hours' => [
                    'monday' => '9am - 5pm',
                    'tuesday' => '9am - 5pm',
                    'wednesday' => '9am - 5pm',
                    'thursday' => '9am - 5pm',
                    'friday' => '9am - 12pm, 2:30pm - 5pm',
                    'saturday' => '10am - 3pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://pasirmasgreen.example.com',
                'waste_types' => [$metalType, $brownGlassType, $greenGlassType, $biologicalType],
            ],
            [
                'name' => 'Tumpat Recycle Station',
                'address' => '34 Jalan Tumpat, Tumpat, Kelantan 16200',
                'phone' => '(09) 555-1357',
                'latitude' => 6.1992,
                'longitude' => 102.1702,
                'hours' => [
                    'monday' => '8am - 7pm',
                    'tuesday' => '8am - 7pm',
                    'wednesday' => '8am - 7pm',
                    'thursday' => '8am - 7pm',
                    'friday' => '8am - 12pm, 2:30pm - 7pm',
                    'saturday' => '9am - 5pm',
                    'sunday' => '10am - 2pm',
                ],
                'website' => 'http://tumpatrecycle.example.com',
                'waste_types' => [$clothesType, $shoesType, $batteryType, $trashType],
            ],
            
            // Melaka
            [
                'name' => 'Melaka City Recycling Hub',
                'address' => '10 Jalan Kota, Melaka City, Melaka 75000',
                'phone' => '(06) 555-8765',
                'latitude' => 2.1896,
                'longitude' => 102.2501,
                'hours' => [
                    'monday' => '8am - 6pm',
                    'tuesday' => '8am - 6pm',
                    'wednesday' => '8am - 6pm',
                    'thursday' => '8am - 6pm',
                    'friday' => '8am - 12pm, 2:30pm - 6pm',
                    'saturday' => '9am - 4pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://melakarecycling.example.com',
                'waste_types' => [$plasticType, $paperType, $cardboardType, $metalType],
            ],
            [
                'name' => 'Alor Gajah Green Center',
                'address' => '25 Jalan Besar, Alor Gajah, Melaka 78000',
                'phone' => '(06) 555-4321',
                'latitude' => 2.3709,
                'longitude' => 102.2081,
                'hours' => [
                    'monday' => '9am - 5pm',
                    'tuesday' => '9am - 5pm',
                    'wednesday' => '9am - 5pm',
                    'thursday' => '9am - 5pm',
                    'friday' => '9am - 12pm, 2:30pm - 5pm',
                    'saturday' => '10am - 3pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://alorgajahgreen.example.com',
                'waste_types' => [$brownGlassType, $greenGlassType, $whiteGlassType, $batteryType],
            ],
            [
                'name' => 'Jasin Recycling Point',
                'address' => '45 Jalan Merdeka, Jasin, Melaka 77000',
                'phone' => '(06) 555-9876',
                'latitude' => 2.3067,
                'longitude' => 102.4296,
                'hours' => [
                    'monday' => '8am - 7pm',
                    'tuesday' => '8am - 7pm',
                    'wednesday' => '8am - 7pm',
                    'thursday' => '8am - 7pm',
                    'friday' => '8am - 12pm, 2:30pm - 7pm',
                    'saturday' => '9am - 5pm',
                    'sunday' => '10am - 2pm',
                ],
                'website' => 'http://jasinrecycle.example.com',
                'waste_types' => [$biologicalType, $clothesType, $shoesType, $trashType],
            ],
            
            // Negeri Sembilan
            [
                'name' => 'Seremban Recycling Center',
                'address' => '12 Jalan Dato Bandar Tunggal, Seremban, Negeri Sembilan 70000',
                'phone' => '(06) 555-1234',
                'latitude' => 2.7258,
                'longitude' => 101.9381,
                'hours' => [
                    'monday' => '8am - 6pm',
                    'tuesday' => '8am - 6pm',
                    'wednesday' => '8am - 6pm',
                    'thursday' => '8am - 6pm',
                    'friday' => '8am - 12pm, 2:30pm - 6pm',
                    'saturday' => '9am - 4pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://serembanrecycling.example.com',
                'waste_types' => [$paperType, $plasticType, $metalType, $whiteGlassType],
            ],
            [
                'name' => 'Port Dickson Green Station',
                'address' => '8 Jalan Pantai, Port Dickson, Negeri Sembilan 71000',
                'phone' => '(06) 555-5678',
                'latitude' => 2.5184,
                'longitude' => 101.7949,
                'hours' => [
                    'monday' => '9am - 5pm',
                    'tuesday' => '9am - 5pm',
                    'wednesday' => '9am - 5pm',
                    'thursday' => '9am - 5pm',
                    'friday' => '9am - 12pm, 2:30pm - 5pm',
                    'saturday' => '10am - 3pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://pdgreen.example.com',
                'waste_types' => [$brownGlassType, $greenGlassType, $cardboardType, $biologicalType],
            ],
            [
                'name' => 'Nilai Recycling Hub',
                'address' => '22 Jalan BBN, Nilai, Negeri Sembilan 71800',
                'phone' => '(06) 555-9012',
                'latitude' => 2.8236,
                'longitude' => 101.8112,
                'hours' => [
                    'monday' => '8am - 7pm',
                    'tuesday' => '8am - 7pm',
                    'wednesday' => '8am - 7pm',
                    'thursday' => '8am - 7pm',
                    'friday' => '8am - 12pm, 2:30pm - 7pm',
                    'saturday' => '9am - 5pm',
                    'sunday' => '10am - 2pm',
                ],
                'website' => 'http://nilairecycle.example.com',
                'waste_types' => [$clothesType, $shoesType, $batteryType, $trashType],
            ],
            
            // Pahang
            [
                'name' => 'Kuantan Green Center',
                'address' => '15 Jalan Besar, Kuantan, Pahang 25000',
                'phone' => '(09) 555-7654',
                'latitude' => 3.8077,
                'longitude' => 103.3260,
                'hours' => [
                    'monday' => '8am - 6pm',
                    'tuesday' => '8am - 6pm',
                    'wednesday' => '8am - 6pm',
                    'thursday' => '8am - 6pm',
                    'friday' => '8am - 12pm, 2:30pm - 6pm',
                    'saturday' => '9am - 4pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://kuantangreen.example.com',
                'waste_types' => [$plasticType, $paperType, $cardboardType, $metalType],
            ],
            [
                'name' => 'Cameron Highlands Recycling',
                'address' => '5 Jalan Brinchang, Tanah Rata, Pahang 39000',
                'phone' => '(05) 555-2345',
                'latitude' => 4.4729,
                'longitude' => 101.3844,
                'hours' => [
                    'monday' => '9am - 5pm',
                    'tuesday' => '9am - 5pm',
                    'wednesday' => '9am - 5pm',
                    'thursday' => '9am - 5pm',
                    'friday' => '9am - 12pm, 2:30pm - 5pm',
                    'saturday' => '10am - 3pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://cameronrecycle.example.com',
                'waste_types' => [$brownGlassType, $greenGlassType, $whiteGlassType, $biologicalType],
            ],
            [
                'name' => 'Bentong Waste Management',
                'address' => '33 Jalan Setapak, Bentong, Pahang 28700',
                'phone' => '(09) 555-8901',
                'latitude' => 3.5195,
                'longitude' => 101.9074,
                'hours' => [
                    'monday' => '8am - 7pm',
                    'tuesday' => '8am - 7pm',
                    'wednesday' => '8am - 7pm',
                    'thursday' => '8am - 7pm',
                    'friday' => '8am - 12pm, 2:30pm - 7pm',
                    'saturday' => '9am - 5pm',
                    'sunday' => '10am - 2pm',
                ],
                'website' => 'http://bentongrecycle.example.com',
                'waste_types' => [$clothesType, $shoesType, $batteryType, $trashType],
            ],
            
            // Perak
            [
                'name' => 'Ipoh Recycling Station',
                'address' => '18 Jalan Sultan Iskandar, Ipoh, Perak 30000',
                'phone' => '(05) 555-4321',
                'latitude' => 4.5975,
                'longitude' => 101.0901,
                'hours' => [
                    'monday' => '8am - 6pm',
                    'tuesday' => '8am - 6pm',
                    'wednesday' => '8am - 6pm',
                    'thursday' => '8am - 6pm',
                    'friday' => '8am - 12pm, 2:30pm - 6pm',
                    'saturday' => '9am - 4pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://ipohrecycling.example.com',
                'waste_types' => [$paperType, $plasticType, $metalType, $cardboardType],
            ],
            [
                'name' => 'Taiping Green Hub',
                'address' => '9 Jalan Taming Sari, Taiping, Perak 34000',
                'phone' => '(05) 555-8765',
                'latitude' => 4.8526,
                'longitude' => 100.7395,
                'hours' => [
                    'monday' => '9am - 5pm',
                    'tuesday' => '9am - 5pm',
                    'wednesday' => '9am - 5pm',
                    'thursday' => '9am - 5pm',
                    'friday' => '9am - 12pm, 2:30pm - 5pm',
                    'saturday' => '10am - 3pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://taipinggreen.example.com',
                'waste_types' => [$whiteGlassType, $brownGlassType, $greenGlassType, $biologicalType],
            ],
            [
                'name' => 'Teluk Intan Recycling Center',
                'address' => '27 Jalan Changkat, Teluk Intan, Perak 36000',
                'phone' => '(05) 555-1098',
                'latitude' => 4.0017,
                'longitude' => 101.0310,
                'hours' => [
                    'monday' => '8am - 7pm',
                    'tuesday' => '8am - 7pm',
                    'wednesday' => '8am - 7pm',
                    'thursday' => '8am - 7pm',
                    'friday' => '8am - 12pm, 2:30pm - 7pm',
                    'saturday' => '9am - 5pm',
                    'sunday' => '10am - 2pm',
                ],
                'website' => 'http://telukintan.example.com',
                'waste_types' => [$clothesType, $shoesType, $batteryType, $trashType],
            ],
            
            // Perlis
            [
                'name' => 'Kangar Recycling Hub',
                'address' => '7 Jalan Jubli Emas, Kangar, Perlis 01000',
                'phone' => '(04) 555-6543',
                'latitude' => 6.4336,
                'longitude' => 100.1938,
                'hours' => [
                    'monday' => '8am - 6pm',
                    'tuesday' => '8am - 6pm',
                    'wednesday' => '8am - 6pm',
                    'thursday' => '8am - 6pm',
                    'friday' => '8am - 12pm, 2:30pm - 6pm',
                    'saturday' => '9am - 4pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://kangarrecycling.example.com',
                'waste_types' => [$plasticType, $paperType, $cardboardType, $metalType],
            ],
            [
                'name' => 'Arau Green Station',
                'address' => '12 Jalan Raja, Arau, Perlis 02600',
                'phone' => '(04) 555-3210',
                'latitude' => 6.4292,
                'longitude' => 100.2698,
                'hours' => [
                    'monday' => '9am - 5pm',
                    'tuesday' => '9am - 5pm',
                    'wednesday' => '9am - 5pm',
                    'thursday' => '9am - 5pm',
                    'friday' => '9am - 12pm, 2:30pm - 5pm',
                    'saturday' => '10am - 3pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://araugreen.example.com',
                'waste_types' => [$brownGlassType, $greenGlassType, $whiteGlassType, $batteryType],
            ],
            [
                'name' => 'Padang Besar Recyclers',
                'address' => '3 Jalan Pasar, Padang Besar, Perlis 02100',
                'phone' => '(04) 555-7890',
                'latitude' => 6.6598,
                'longitude' => 100.3218,
                'hours' => [
                    'monday' => '8am - 7pm',
                    'tuesday' => '8am - 7pm',
                    'wednesday' => '8am - 7pm',
                    'thursday' => '8am - 7pm',
                    'friday' => '8am - 12pm, 2:30pm - 7pm',
                    'saturday' => '9am - 5pm',
                    'sunday' => '10am - 2pm',
                ],
                'website' => 'http://padangbesarrecycle.example.com',
                'waste_types' => [$biologicalType, $clothesType, $shoesType, $trashType],
            ],
            
            // Pulau Pinang (Penang)
            [
                'name' => 'Georgetown Recycling Center',
                'address' => '25 Jalan Penang, Georgetown, Pulau Pinang 10000',
                'phone' => '(04) 555-2109',
                'latitude' => 5.4164,
                'longitude' => 100.3327,
                'hours' => [
                    'monday' => '8am - 6pm',
                    'tuesday' => '8am - 6pm',
                    'wednesday' => '8am - 6pm',
                    'thursday' => '8am - 6pm',
                    'friday' => '8am - 12pm, 2:30pm - 6pm',
                    'saturday' => '9am - 4pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://georgetownrecycling.example.com',
                'waste_types' => [$paperType, $plasticType, $metalType, $cardboardType],
            ],
            [
                'name' => 'Butterworth Green Hub',
                'address' => '17 Jalan Chain Ferry, Butterworth, Pulau Pinang 12100',
                'phone' => '(04) 555-6789',
                'latitude' => 5.3992,
                'longitude' => 100.3639,
                'hours' => [
                    'monday' => '9am - 5pm',
                    'tuesday' => '9am - 5pm',
                    'wednesday' => '9am - 5pm',
                    'thursday' => '9am - 5pm',
                    'friday' => '9am - 12pm, 2:30pm - 5pm',
                    'saturday' => '10am - 3pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://butterworthgreen.example.com',
                'waste_types' => [$whiteGlassType, $brownGlassType, $greenGlassType, $biologicalType],
            ],
            [
                'name' => 'Bayan Lepas Recycling Point',
                'address' => '8 Jalan Mahsuri, Bayan Lepas, Pulau Pinang 11950',
                'phone' => '(04) 555-0123',
                'latitude' => 5.3367,
                'longitude' => 100.3091,
                'hours' => [
                    'monday' => '8am - 7pm',
                    'tuesday' => '8am - 7pm',
                    'wednesday' => '8am - 7pm',
                    'thursday' => '8am - 7pm',
                    'friday' => '8am - 12pm, 2:30pm - 7pm',
                    'saturday' => '9am - 5pm',
                    'sunday' => '10am - 2pm',
                ],
                'website' => 'http://bayanlepasrecycle.example.com',
                'waste_types' => [$clothesType, $shoesType, $batteryType, $trashType],
            ],
            
            // Sabah
            [
                'name' => 'Kota Kinabalu Recycling Hub',
                'address' => '20 Jalan Gaya, Kota Kinabalu, Sabah 88000',
                'phone' => '(088) 555-3456',
                'latitude' => 5.9804,
                'longitude' => 116.0735,
                'hours' => [
                    'monday' => '8am - 6pm',
                    'tuesday' => '8am - 6pm',
                    'wednesday' => '8am - 6pm',
                    'thursday' => '8am - 6pm',
                    'friday' => '8am - 12pm, 2:30pm - 6pm',
                    'saturday' => '9am - 4pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://kkrecyclinghub.example.com',
                'waste_types' => [$plasticType, $paperType, $cardboardType, $metalType],
            ],
            [
                'name' => 'Sandakan Green Center',
                'address' => '12 Jalan Pelabuhan, Sandakan, Sabah 90000',
                'phone' => '(089) 555-7654',
                'latitude' => 5.8402,
                'longitude' => 118.1179,
                'hours' => [
                    'monday' => '9am - 5pm',
                    'tuesday' => '9am - 5pm',
                    'wednesday' => '9am - 5pm',
                    'thursday' => '9am - 5pm',
                    'friday' => '9am - 12pm, 2:30pm - 5pm',
                    'saturday' => '10am - 3pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://sandakangreen.example.com',
                'waste_types' => [$brownGlassType, $greenGlassType, $whiteGlassType, $batteryType],
            ],
            [
                'name' => 'Tawau Recycling Station',
                'address' => '35 Jalan St. Patrick, Tawau, Sabah 91000',
                'phone' => '(089) 555-2109',
                'latitude' => 4.2498,
                'longitude' => 117.8871,
                'hours' => [
                    'monday' => '8am - 7pm',
                    'tuesday' => '8am - 7pm',
                    'wednesday' => '8am - 7pm',
                    'thursday' => '8am - 7pm',
                    'friday' => '8am - 12pm, 2:30pm - 7pm',
                    'saturday' => '9am - 5pm',
                    'sunday' => '10am - 2pm',
                ],
                'website' => 'http://tawaurecycle.example.com',
                'waste_types' => [$biologicalType, $clothesType, $shoesType, $trashType],
            ],
            
            // Sarawak
            [
                'name' => 'Kuching Recycling Center',
                'address' => '15 Jalan Padungan, Kuching, Sarawak 93100',
                'phone' => '(082) 555-8976',
                'latitude' => 1.5535,
                'longitude' => 110.3593,
                'hours' => [
                    'monday' => '8am - 6pm',
                    'tuesday' => '8am - 6pm',
                    'wednesday' => '8am - 6pm',
                    'thursday' => '8am - 6pm',
                    'friday' => '8am - 12pm, 2:30pm - 6pm',
                    'saturday' => '9am - 4pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://kuchingrecycling.example.com',
                'waste_types' => [$paperType, $plasticType, $metalType, $cardboardType],
            ],
            [
                'name' => 'Miri Green Hub',
                'address' => '27 Jalan Yu Seng, Miri, Sarawak 98000',
                'phone' => '(085) 555-4321',
                'latitude' => 4.3899,
                'longitude' => 113.9913,
                'hours' => [
                    'monday' => '9am - 5pm',
                    'tuesday' => '9am - 5pm',
                    'wednesday' => '9am - 5pm',
                    'thursday' => '9am - 5pm',
                    'friday' => '9am - 12pm, 2:30pm - 5pm',
                    'saturday' => '10am - 3pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://mirigreen.example.com',
                'waste_types' => [$whiteGlassType, $brownGlassType, $greenGlassType, $biologicalType],
            ],
            [
                'name' => 'Sibu Recycling Station',
                'address' => '8 Jalan Channel, Sibu, Sarawak 96000',
                'phone' => '(084) 555-3210',
                'latitude' => 2.3021,
                'longitude' => 111.8425,
                'hours' => [
                    'monday' => '8am - 7pm',
                    'tuesday' => '8am - 7pm',
                    'wednesday' => '8am - 7pm',
                    'thursday' => '8am - 7pm',
                    'friday' => '8am - 12pm, 2:30pm - 7pm',
                    'saturday' => '9am - 5pm',
                    'sunday' => '10am - 2pm',
                ],
                'website' => 'http://siburecycle.example.com',
                'waste_types' => [$clothesType, $shoesType, $batteryType, $trashType],
            ],
            
            // Selangor
            [
                'name' => 'Shah Alam Recycling Hub',
                'address' => '22 Jalan Persiaran Damai, Shah Alam, Selangor 40000',
                'phone' => '(03) 555-1234',
                'latitude' => 3.0738,
                'longitude' => 101.5183,
                'hours' => [
                    'monday' => '8am - 6pm',
                    'tuesday' => '8am - 6pm',
                    'wednesday' => '8am - 6pm',
                    'thursday' => '8am - 6pm',
                    'friday' => '8am - 12pm, 2:30pm - 6pm',
                    'saturday' => '9am - 4pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://shahalam.example.com',
                'waste_types' => [$plasticType, $paperType, $cardboardType, $metalType],
            ],
            [
                'name' => 'Petaling Jaya Green Center',
                'address' => '17 Jalan Utara, Petaling Jaya, Selangor 46200',
                'phone' => '(03) 555-5678',
                'latitude' => 3.1073,
                'longitude' => 101.6063,
                'hours' => [
                    'monday' => '9am - 5pm',
                    'tuesday' => '9am - 5pm',
                    'wednesday' => '9am - 5pm',
                    'thursday' => '9am - 5pm',
                    'friday' => '9am - 12pm, 2:30pm - 5pm',
                    'saturday' => '10am - 3pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://pjgreen.example.com',
                'waste_types' => [$brownGlassType, $greenGlassType, $whiteGlassType, $biologicalType],
            ],
            [
                'name' => 'Klang Recycling Station',
                'address' => '8 Jalan Dato Hamzah, Klang, Selangor 41000',
                'phone' => '(03) 555-9012',
                'latitude' => 3.0449,
                'longitude' => 101.4455,
                'hours' => [
                    'monday' => '8am - 7pm',
                    'tuesday' => '8am - 7pm',
                    'wednesday' => '8am - 7pm',
                    'thursday' => '8am - 7pm',
                    'friday' => '8am - 12pm, 2:30pm - 7pm',
                    'saturday' => '9am - 5pm',
                    'sunday' => '10am - 2pm',
                ],
                'website' => 'http://klangrecycle.example.com',
                'waste_types' => [$clothesType, $shoesType, $batteryType, $trashType],
            ],
            
            // Terengganu
            [
                'name' => 'Kuala Terengganu Recycling Hub',
                'address' => '9 Jalan Sultan Zainal Abidin, Kuala Terengganu, Terengganu 20000',
                'phone' => '(09) 555-6789',
                'latitude' => 5.3302,
                'longitude' => 103.1408,
                'hours' => [
                    'monday' => '8am - 6pm',
                    'tuesday' => '8am - 6pm',
                    'wednesday' => '8am - 6pm',
                    'thursday' => '8am - 6pm',
                    'friday' => '8am - 12pm, 2:30pm - 6pm',
                    'saturday' => '9am - 4pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://ktrecycling.example.com',
                'waste_types' => [$paperType, $plasticType, $metalType, $cardboardType],
            ],
            [
                'name' => 'Kemaman Green Center',
                'address' => '18 Jalan Sulaimani, Chukai, Terengganu 24000',
                'phone' => '(09) 555-3456',
                'latitude' => 4.2265,
                'longitude' => 103.4449,
                'hours' => [
                    'monday' => '9am - 5pm',
                    'tuesday' => '9am - 5pm',
                    'wednesday' => '9am - 5pm',
                    'thursday' => '9am - 5pm',
                    'friday' => '9am - 12pm, 2:30pm - 5pm',
                    'saturday' => '10am - 3pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://kemamangreen.example.com',
                'waste_types' => [$whiteGlassType, $brownGlassType, $greenGlassType, $biologicalType],
            ],
            [
                'name' => 'Dungun Recycling Point',
                'address' => '5 Jalan Besar, Dungun, Terengganu 23000',
                'phone' => '(09) 555-7890',
                'latitude' => 4.7580,
                'longitude' => 103.4211,
                'hours' => [
                    'monday' => '8am - 7pm',
                    'tuesday' => '8am - 7pm',
                    'wednesday' => '8am - 7pm',
                    'thursday' => '8am - 7pm',
                    'friday' => '8am - 12pm, 2:30pm - 7pm',
                    'saturday' => '9am - 5pm',
                    'sunday' => '10am - 2pm',
                ],
                'website' => 'http://dungunrecycle.example.com',
                'waste_types' => [$clothesType, $shoesType, $batteryType, $trashType],
            ],
            
            // Kuala Lumpur (Federal Territory)
            [
                'name' => 'KL City Recycling Hub',
                'address' => '25 Jalan Tun Razak, Kuala Lumpur 50400',
                'phone' => '(03) 555-2345',
                'latitude' => 3.1590,
                'longitude' => 101.7102,
                'hours' => [
                    'monday' => '8am - 6pm',
                    'tuesday' => '8am - 6pm',
                    'wednesday' => '8am - 6pm',
                    'thursday' => '8am - 6pm',
                    'friday' => '8am - 12pm, 2:30pm - 6pm',
                    'saturday' => '9am - 4pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://klcityrecycling.example.com',
                'waste_types' => [$plasticType, $paperType, $cardboardType, $metalType],
            ],
            [
                'name' => 'Cheras Green Center',
                'address' => '12 Jalan Cheras, Kuala Lumpur 56100',
                'phone' => '(03) 555-6789',
                'latitude' => 3.1073,
                'longitude' => 101.7427,
                'hours' => [
                    'monday' => '9am - 5pm',
                    'tuesday' => '9am - 5pm',
                    'wednesday' => '9am - 5pm',
                    'thursday' => '9am - 5pm',
                    'friday' => '9am - 12pm, 2:30pm - 5pm',
                    'saturday' => '10am - 3pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://cherasgreen.example.com',
                'waste_types' => [$brownGlassType, $greenGlassType, $whiteGlassType, $biologicalType],
            ],
            [
                'name' => 'Sentul Recycling Station',
                'address' => '8 Jalan Sentul, Kuala Lumpur 51000',
                'phone' => '(03) 555-0123',
                'latitude' => 3.1851,
                'longitude' => 101.6926,
                'hours' => [
                    'monday' => '8am - 7pm',
                    'tuesday' => '8am - 7pm',
                    'wednesday' => '8am - 7pm',
                    'thursday' => '8am - 7pm',
                    'friday' => '8am - 12pm, 2:30pm - 7pm',
                    'saturday' => '9am - 5pm',
                    'sunday' => '10am - 2pm',
                ],
                'website' => 'http://sentulrecycle.example.com',
                'waste_types' => [$clothesType, $shoesType, $batteryType, $trashType],
            ],
            
            // Labuan (Federal Territory)
            [
                'name' => 'Labuan Recycling Hub',
                'address' => '10 Jalan Merdeka, Labuan 87000',
                'phone' => '(087) 555-4567',
                'latitude' => 5.2830,
                'longitude' => 115.2308,
                'hours' => [
                    'monday' => '8am - 6pm',
                    'tuesday' => '8am - 6pm',
                    'wednesday' => '8am - 6pm',
                    'thursday' => '8am - 6pm',
                    'friday' => '8am - 12pm, 2:30pm - 6pm',
                    'saturday' => '9am - 4pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://labuanrecycling.example.com',
                'waste_types' => [$paperType, $plasticType, $metalType, $cardboardType],
            ],
            [
                'name' => 'Victoria Point Green Center',
                'address' => '5 Jalan Tun Mustapha, Labuan 87007',
                'phone' => '(087) 555-8910',
                'latitude' => 5.2772,
                'longitude' => 115.2425,
                'hours' => [
                    'monday' => '9am - 5pm',
                    'tuesday' => '9am - 5pm',
                    'wednesday' => '9am - 5pm',
                    'thursday' => '9am - 5pm',
                    'friday' => '9am - 12pm, 2:30pm - 5pm',
                    'saturday' => '10am - 3pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://victoriapoint.example.com',
                'waste_types' => [$whiteGlassType, $brownGlassType, $greenGlassType, $biologicalType],
            ],
            [
                'name' => 'Labuan Town Recycling Point',
                'address' => '22 Jalan Dewan, Labuan 87008',
                'phone' => '(087) 555-3210',
                'latitude' => 5.2714,
                'longitude' => 115.2476,
                'hours' => [
                    'monday' => '8am - 7pm',
                    'tuesday' => '8am - 7pm',
                    'wednesday' => '8am - 7pm',
                    'thursday' => '8am - 7pm',
                    'friday' => '8am - 12pm, 2:30pm - 7pm',
                    'saturday' => '9am - 5pm',
                    'sunday' => '10am - 2pm',
                ],
                'website' => 'http://labuantownrecycle.example.com',
                'waste_types' => [$clothesType, $shoesType, $batteryType, $trashType],
            ],
            
            // Putrajaya (Federal Territory)
            [
                'name' => 'Putrajaya Recycling Center',
                'address' => '15 Persiaran Perdana, Putrajaya 62000',
                'phone' => '(03) 555-7654',
                'latitude' => 2.9188,
                'longitude' => 101.6781,
                'hours' => [
                    'monday' => '8am - 6pm',
                    'tuesday' => '8am - 6pm',
                    'wednesday' => '8am - 6pm',
                    'thursday' => '8am - 6pm',
                    'friday' => '8am - 12pm, 2:30pm - 6pm',
                    'saturday' => '9am - 4pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://putrajayarecycling.example.com',
                'waste_types' => [$plasticType, $paperType, $cardboardType, $metalType],
            ],
            [
                'name' => 'Precinct 9 Green Hub',
                'address' => '7 Jalan P9, Putrajaya 62250',
                'phone' => '(03) 555-2109',
                'latitude' => 2.9329,
                'longitude' => 101.6719,
                'hours' => [
                    'monday' => '9am - 5pm',
                    'tuesday' => '9am - 5pm',
                    'wednesday' => '9am - 5pm',
                    'thursday' => '9am - 5pm',
                    'friday' => '9am - 12pm, 2:30pm - 5pm',
                    'saturday' => '10am - 3pm',
                    'sunday' => 'Closed',
                ],
                'website' => 'http://precinct9green.example.com',
                'waste_types' => [$brownGlassType, $greenGlassType, $whiteGlassType, $biologicalType],
            ],
            [
                'name' => 'Putrajaya Lake Recycling Point',
                'address' => '3 Persiaran Tasik, Putrajaya 62050',
                'phone' => '(03) 555-8765',
                'latitude' => 2.9310,
                'longitude' => 101.6853,
                'hours' => [
                    'monday' => '8am - 7pm',
                    'tuesday' => '8am - 7pm',
                    'wednesday' => '8am - 7pm',
                    'thursday' => '8am - 7pm',
                    'friday' => '8am - 12pm, 2:30pm - 7pm',
                    'saturday' => '9am - 5pm',
                    'sunday' => '10am - 2pm',
                ],
                'website' => 'http://putrajayalake.example.com',
                'waste_types' => [$clothesType, $shoesType, $batteryType, $trashType],
            ],
        ];

        foreach ($centers as $centerData) {
            $wasteTypes = $centerData['waste_types'];
            unset($centerData['waste_types']);

            $center = RecyclingCenter::create($centerData);

            // Attach waste types
            foreach ($wasteTypes as $wasteType) {
                if ($wasteType) {
                    $center->wasteTypes()->attach($wasteType->id);
                }
            }
        }
    }
}